### ISSUE TITLE
No building list available for voiceover users unless the map has been panned.

### ISSUE THREAD

**Issue by colingor** [edina/Estates-Audit#118]
The buildings list is only populated when the map is manually scrolled and a bounding box search is sent to Elastic Search.  This is no good for voiceover users and as such the building list is empty.  If voiceover is on when the page loads, we should perform a distance search from the current location to populate the building list instead.

**Comment by benismobile** [comment]
good spot - but not sure relying on voiceover activation is enough as there may be non voice over users who have preference for list rather than map.
