### ISSUE TITLE
Improve the colour contrast of the grey text on the grey background

### ISSUE THREAD

**Issue by benismobile** [edina/Estates-Audit#124]
see accessibility report Viki Galt

**Comment by colingor** [comment]
Some examples of new text colour in labels which should improve contrast:

![screen shot 2015-08-27 at 14 33 10](https://cloud.githubusercontent.com/assets/770283/9521748/8e97f718-4cc8-11e5-8e4f-ff53757fe13e.png)
![screen shot 2015-08-27 at 14 33 38](https://cloud.githubusercontent.com/assets/770283/9521747/8e93ae2e-4cc8-11e5-82c6-4070bd84d1ff.png)
![screen shot 2015-08-27 at 14 33 50](https://cloud.githubusercontent.com/assets/770283/9521749/8e98dbce-4cc8-11e5-9349-417289d43ed5.png)
