### ISSUE TITLE
Label the camera icons and the roll of film icons 

### ISSUE THREAD

**Issue by benismobile** [edina/Estates-Audit#126]
see accessibility report (VG)

**Comment by colingor** [comment]
Added labels as can be seen below:

![screen shot 2015-08-26 at 11 21 44](https://cloud.githubusercontent.com/assets/770283/9491104/830e4fe4-4be4-11e5-92f1-93573e366ca3.png)

**Comment by benismobile** [comment]
that looks great. Can we check this doesn't screw up with VoiceOver.

**Comment by colingor** [comment]
I've configured it so voiceover will ignore the labels completely and only read out the hints associated with the 2 buttons to prevent duplication.
