### ISSUE TITLE
building facilities list selector

### ISSUE THREAD

**Issue by benismobile** [edina/Estates-Audit#15]
when user selects a building from nearby buildings list a new list of facilities within that building (e.g. toilets second floor are displayed - user can select from this list and text in location description text box is updated accordingly. 

question - can we do this in keyboard in same way word suggestions appear?

**Comment by benismobile** [comment]
we will provide some records for the metadata - we can do this using PC_API?

**Comment by benismobile** [comment]
we could also show users pictures of the facilities if available ( most are in estates and building pdf guides)

**Comment by ianfieldhouse** [comment]
Commit ff0ea958e5182785d5ea004f413ff3641ac0a2f6 adds marker pins to the MapView for UoE Estates buildings. Clicking on a  map pin reveals a pop over with details of the location. 

This is only the first step to the required functionality.

**Comment by benismobile** [comment]
so adding a textual selector of some kind as alternative to picking building from map is needed, especially for Voice Over users. Voice Over users should get to this before the map so they can avoid map altogether.
