### ISSUE TITLE
Request for tickets only loads 10 by default

### ISSUE THREAD

**Issue by colingor** [edina/Estates-Audit#48]
If there are more than 10 tickets, we won't see the oldest one.  The jitbit API allows us to specify a count and an offset to get further tickets.  We should investigate calling the next page of results when a user gets near the bottom of the reports table list perhaps

**Comment by benismobile** [comment]
i think it might be better not to crowd the screen with old tickets - i'd even suggest we reduce down to 5

**Comment by colingor** [comment]
should we still show closed tickets?

**Comment by benismobile** [comment]
yeah i think so - could be there is some disagreement about whether ticket should have been closed so gives student a chance to add a comment.
