### ISSUE TITLE
set up TestFlight

### ISSUE THREAD

**Issue by benismobile** [edina/Estates-Audit#62]
Initially, the users would be:
David Casey – david.casey@ed.ac.uk
Ian Fell – ian.fell@ed.ac.uk
Chris Lesutis – c.lesutis@ed.ac.uk
Jack Peach – jack.peach.ed.ac.uk

**Comment by colingor** [comment]
App has been submitted for review and testers emails added to Itunes Connect

**Comment by colingor** [comment]
Invites sent

**Comment by benismobile** [comment]
could you add me: b.butchart@gmail.com

**Comment by benismobile** [comment]
I installed app from TestFlight but does not seem to have buildings list populated.

**Comment by colingor** [comment]
I'll update the build this morning

**Comment by benismobile** [comment]
Cool thx

**Comment by colingor** [comment]
Tagged 99098d1 and uploaded to TestFlight.  Invites also sent out
