### ISSUE TITLE
change "comments" tab text to "status"

### ISSUE THREAD

**Issue by benismobile** [edina/Estates-Audit#65]
comments just sounds a bit social media to me!

**Comment by benismobile** [comment]
actually perhaps better than "status" would be "updates"? 
Also the button in top right corner for adding a comment has an icon which made me think it was a Back button. Perhaps we can replace this icon with the chat icon?

**Comment by colingor** [comment]
See attached screenshot to see what it looks like now:

![ios simulator screen shot 3 jun 2015 11 43 03](https://cloud.githubusercontent.com/assets/770283/7958272/b8a18c3e-09e5-11e5-9c99-41424fed78d3.png)

**Comment by benismobile** [comment]
looks good to me!
